apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /api/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-service
            port:
              number: 8082
      - path: /upload
        pathType: ImplementationSpecific
        backend:
          service:
            name: file-uploader-service
            port:
              number: 8083
      - path: /metadata/update
        pathType: ImplementationSpecific
        backend:
          service:
            name: ai-updates-service
            port:
              number: 8084
      - path: /metadata/retrieve_list
        pathType: ImplementationSpecific
        backend:
          service:
            name: ai-updates-service
            port:
              number: 8084
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: demo-frontend-service
            port:
              number: 8081
