options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the Docker image and tag it with both the commit SHA and 'latest'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:latest'
      - '${_SERVICE_DIR}'

  # Push the image tagged as 'latest' to the registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:latest'

  # Get credentials for the Kubernetes cluster, apply deployments and update the Kubernetes deployment's image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials ${_PROJECT_ID} --region=${_REGION} --project=${_PROJECT_ID} &&
        kubectl apply -f DevOps/${_SERVICE_DIR}.yaml &&
        kubectl set image deployment/${_IMAGE_NAME}-deployment ${_IMAGE_NAME}=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:latest --namespace=default

images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:latest'
