options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the Docker image and tag it with both the commit SHA and 'latest'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:latest'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA'
      - '${_SERVICE_DIR}'

  # Push the image tagged as 'latest' to the registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:latest'

  # Push the image tagged with the commit SHA to the registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA'

  # Get credentials for the Kubernetes cluster, apply deployments and update the Kubernetes deployment's image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials hackathon-cluster --region=${_REGION} --project=$PROJECT_ID &&
        kubectl apply -f DevOps/deployments/${_IMAGE_NAME}.yaml &&
        kubectl set image deployment/app-${_IMAGE_NAME} ${_IMAGE_NAME}=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:latest --namespace=default

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA'
