apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-frontend
  template:
    metadata:
      labels:
        app: app-frontend
    spec:
      containers:
      - name: frontend
        image: me-west1-docker.pkg.dev/hackathon-082024/hackathon-repo/frontend:$SHORT_SHA
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  selector:
    app: app-frontend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 3000
