apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-media
  template:
    metadata:
      labels:
        app: app-media
    spec:
      containers:
      - name: app-media
        image: me-west1-docker.pkg.dev/hackathon-082024/hackathon-repo/media:$SHORT_SHA
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: media-service
spec:
  type: ClusterIP
  selector:
    app: app-media
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8080
